project/stepshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit


app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

project/stepshop/basketapp/urls.py
from django.urls import path
from basketapp.views import basket, basket_add, basket_remove

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
]

project/stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts, about


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/stepshop/basketapp/models.py
from django.db import models
from stepshop import settings
from mainapp.models import Product

class Basket(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='basket'
    )

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество',
        default=0,
    )

    add_datetime = models.DateTimeField(
        verbose_name='время',
        auto_now_add=True,
    )

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        _total_quantity = sum(list(map(lambda x: x.quantity, _items)))
        return _total_quantity

    @property
    def total_cost(self):
        _items = Basket.objects.filter(user=self.user)
        _total_cost = sum(list(map(lambda x: x.product_cost, _items)))
        return _total_cost

project/stepshop/basketapp/views.py
from django.shortcuts import render, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product
from django.http import HttpResponseRedirect


def basket(request):
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        context = {
            'basket': basket
        }
        return render(request, 'basketapp/basket.html', context)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_add(request, pk):
    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product= product).first()

    if not basket: 
        basket = Basket(user=request.user, product= product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_remove(request, pk):
    aaa = get_object_or_404(Basket, pk=pk)
    aaa.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

project/stepshop/basketapp/templates/basketapp/basket.html
{% extends 'stepshop/base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
    {% if basket %}
    <br><br>
    <div class="container" style="margin-top: 130px;">
        <div style="font-size: 18px; text-align: center;"> 

            There are <strong>{{ basket.0.total_quantity }}</strong> 
            products in the cart with a total value of 
            <strong>${{ basket.0.total_cost }}</strong>
            
        </div>
            
        <br>
        <div class="row">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Продукт</th>
                            <th scope="col">Количество</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in basket %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{item.product}}</td>
                            <td>{{item.quantity}}</td>
                            <td><button class="btn btn-round">
                                <a href="{% url 'basket:remove' item.pk %}">delete</a>
                            </button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
    <div class="container" style="margin-top: 130px;">
        <div class="row" style="height: 700px;">
            <h6 style="margin: auto;">You have no items in your cart.</h6>
        </div>
    </div>
    {% endif %}
{% endif %}

{% endblock %}