project/stepshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit


app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

project/stepshop/basketapp/urls.py
from django.urls import path
from basketapp.views import basket, basket_add, basket_remove

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
]

project/stepshop/mainapp/urls.py
from django.urls import path
from .views import products, product
from django.conf import settings
from django.conf.urls.static import static


app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>', products, name='category'),
    path('product/<int:pk>', product, name='product'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts, about


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/stepshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    def __str__(self):
        return self.name or f'Category with id - {self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='product_images',
        blank=True,
        verbose_name='изображение',
    )

    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=100,
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество товара на складе',
        default=0,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name or f'Product with id - {self.pk}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

project/stepshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
from basketapp.models import Basket
from stepshop.views import get_basket_quentity

def products(req, pk=None):
    context = {
        'links_menu': ProductCategory.objects.all(),
        'products': Product.objects.all().order_by('price')
    }

    basket = []

    if req.user.is_authenticated:
        basket = Basket.objects.filter(user=req.user)


    if pk is not None:
        context['products'] = Product.objects.filter(category__pk=pk).order_by('price')
    context['basket'] = basket

    return render(request=req,template_name='mainapp/products.html', context=context)


def product(request, pk):
    context = {
        'links_menu': ProductCategory.objects.all(),
        'all_products': Product.objects.filter(category__pk=ProductCategory.objects.get(name=Product.objects.get(pk=pk).category).pk).exclude(pk=pk),
        'product': get_object_or_404(Product, pk=pk),
        'basket':get_basket_quentity(request),
        'category_id': ProductCategory.objects.get(name=Product.objects.get(pk=pk).category).pk
    }

    return render(request=request,template_name='mainapp/product.html', context=context)

project/stepshop/mainapp/templates/mainapp/product.html
{% extends 'stepshop/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content -->
    <!-- Single Starts Here -->
    <br><br>
    <div class="single-product">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Product</h1>
            </div>
          </div>
          <div class="col-md-6">
            <img src="/media/{{product.image}}" style="width: 33rem;">
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>{{product.name}}</h4>
              <h6>${{product.price}}</h6>
              <p style="word-wrap: break-word;">{{product.description}}</p>
              <span>{{product.quantity}} left on stock</span><br>
              {% if user.is_authenticated %}
              <a href="{% url 'basket:add' product.pk %}" class="btn btn-primary">Add to cart</a>
              {% else %}
              <a href="{% url 'basket:add' product.pk %}" style="pointer-events: none; cursor: default; background-color: #888;" class="btn btn-primary">Add to cart</a>
              <br><small class="text-muted">In order to add a product to the cart, register or log in</small>
              {% endif %}
              <div class="down-content">
                <div class="categories">
                  <h6>Category: 
                    <span>
                      <a href="{% url 'products:category' category_id %}">{{product.category}}</a>
                    </span>
                  </h6>
                </div>
                <div class="share">
                  <h6>Share: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Single Page Ends Here -->


    <!-- Similar Starts Here -->
    <div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>You May Also Like</h1>
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-carousel owl-theme">
              {% for item in all_products %}
              <a href="{% url 'products:product' item.pk %}">
                <div class="featured-item">
                  <img src="/media/{{ item.image }}" alt="{{ item.short_desc }}">
                    <h4>{{ item.name }}</h4>
                    <h6>${{ item.price }}</h6>
                </div>
              </a>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Similar Ends Here -->
{% endblock %}

project/stepshop/mainapp/templates/mainapp/products.html
{% extends 'stepshop/base.html' %}
{% load static %}
{% load pic_tags %}


{% block content %}



    {% include  'mainapp/includes/inc_category_menu.html' %}
  
    <div class="featured container no-gutter">

        <div class="row posts">
          {% for item in products %}
            <div id="{{item.pk}}" class="item new col-md-4">
              <a href="{% url 'products:product' item.pk %}">
                <div class="featured-item">
                  <img src="{{ item.image|media_folder_products }}" alt="{{ item.short_desc }}">
                  <h4>{{item.name}}</h4>
                  <h6>${{item.price}}</h6>
                </div>
              </a>
            </div>
          {% endfor %}
        </div>
    </div>

        <!-- Bootstrap core JavaScript -->
    <script src="{% static 'stepshop/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'stepshop/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'stepshop/js/custom.js' %}"></script>
    <script src="{% static 'stepshop/js/owl.js' %}"></script>
    <script src="{% static 'stepshop/js/isotope.js' %}"></script>
    <script src="{% static 'stepshop/js/flex-slider.js' %}"></script>
    <!-- Featred Page Ends Here -->
{% endblock %}

   