project/stepshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit


app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

project/stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts, about


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/stepshop/stepshop/views.py
from django.shortcuts import render
from mainapp.models import Product
from basketapp.models import Basket


def get_basket_quentity(request):
    if request.user.is_authenticated:
        return Basket.objects.filter(user=request.user)


def index(request):
    products = Product.objects.all()[:4]


    context = {
        'products': products,
        'basket': get_basket_quentity(request),
    }

    return render(request, 'stepshop/index.html', context=context)


def contacts(request):
    return render(request, 'stepshop/contact.html', context={'basket': get_basket_quentity(request),})


def about(request):
    return render(request, 'stepshop/about.html', context={'basket': get_basket_quentity(request),})

project/stepshop/stepshop/templates/stepshop/includes/inc_main_menu.html
    <!-- Navigation -->
{% load static %}

    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <div class="navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
              <li class="nav-item {% if request.resolver_match.route == '' %}active{% endif %}">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item {% if request.resolver_match.route == 'products/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'products:index' %}">Products</a>
              </li>
              <li class="nav-item {% if request.resolver_match.route == 'about/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'about' %}">About&nbsp;Us</a>
              </li>
              <li class="nav-item {% if request.resolver_match.route == 'contacts/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'contacts' %}">Contact&nbsp;Us</a>
              </li>

            </ul>
          </div>
        </div>
      </nav>
      