project/stepshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit


app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

project/stepshop/basketapp/urls.py
from django.urls import path
from basketapp.views import basket, basket_add, basket_remove

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
]

project/stepshop/mainapp/urls.py
from django.urls import path
from .views import products, product
from django.conf import settings
from django.conf.urls.static import static


app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>', products, name='category'),
    path('product/<int:pk>', product, name='product'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts, about


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/stepshop/stepshop/views.py
from django.shortcuts import render
from mainapp.models import Product
from basketapp.models import Basket


def get_basket_quentity(request):
    if request.user.is_authenticated:
        return Basket.objects.filter(user=request.user)


def index(request):
    products = Product.objects.all()[:4]


    context = {
        'products': products,
        'basket': get_basket_quentity(request),
    }

    return render(request, 'stepshop/index.html', context=context)


def contacts(request):
    return render(request, 'stepshop/contact.html', context={'basket': get_basket_quentity(request),})


def about(request):
    return render(request, 'stepshop/about.html', context={'basket': get_basket_quentity(request),})

project/stepshop/stepshop/templates/stepshop/about.html
{% extends 'stepshop/base.html' %}
{% load static %}


{% block content %}
    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="about-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>About Us</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-image">
              <img src="{% static 'stepshop/images/about_us.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <p>0101010101001 01010101101110 10111100001100000001010101001 0101010101010101010101010101 0100000 0101110100100100011010 10010101010101001010101 01010010101010 1101110101111000011000000010101 0100101010101010101 010101010101010100000010 111010010010001101 010010101010101001</p> 
              <br>
              <p>01010111 11010100101010101 101110101100001 111110000110000000101010 100101010101010101011 10101010101010100000010111 010011111001000110 10100101010101111101001</p>
              <br>
              <p>01010101010010101 010110111010111100001 1000000010 1010100101010101010101 01010101010101 0100000010111010010 0100011010100101010101 01001010101 01010010101010110111 01011110000110000000101010100101 010101010101010101010101010100 000010111010010010001101 010010101010101001</p>
              <br> 
              <p>010101010100101 010101101110101111000 0110000000101010100101010 101010101010101010 10101010000001011101 001001000110101001010 101010100101010101 01001010101011011 10101111000011000000010 101010010101010101010 10101010 101010101000 00010111010 010010001101 010010101010101001</p>
              <div class="share">
                <h6>you won't find us on: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->
{% endblock %}

project/stepshop/stepshop/templates/stepshop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>{% block title %} 
      {% if title %}
        {{ title }} 
      {%else%}
        HACK Shop
      {%endif%}


      {% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'stepshop/images/fast-cart.png' %}" type="image/x-icon">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'stepshop/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'stepshop/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'stepshop/css/tooplate-main.css' %}">
    <link rel="stylesheet" href="{% static 'stepshop/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'stepshop/css/style.css' %}">

    {% block css %}
    {% endblock %}

  </head>

  <body>
    
    <!-- Pre Header -->
    <div id="pre-header">
      <div class="container">
        <div class="row" style="height: 2.8rem;">
          <div class="col-md-12" style="text-align: right;">
            {% if user.is_authenticated %}
                <a class="btn btn-light" style="margin-top: 0.2rem;" href="{% url 'auth:edit' %}">
                  Profile
                </a>
              {% endif %}
              
                {% if user.is_authenticated %}
                  <a href="{% url 'basket:view' %}" class="btn btn-light" style="margin-top: 0.2rem;">Cart - {{ basket.0.total_quantity }}</a>
                  <a class="btn btn-light" style="margin-top: 0.2rem;" href="{% url 'auth:logout' %}">Logout</a>
                {% else %}
                  <a class="btn btn-light" style="margin-top: 0.2rem;" href="{% url 'auth:login' %}">Login</a>
                  <a class="btn btn-light" style="margin-top: 0.2rem;" href="{% url 'auth:register' %}" class="">Sing up</a>
                {% endif %}
          </div>
        </div>
      </div>
    </div>

    {% include  'stepshop/includes/inc_main_menu.html' %}

    {% block content %}
    {% endblock %}




    <!-- Sub Footer Starts Here -->
    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="copyright-text">
              <p>Copyright &copy; 2019 - {%now "Y"%} Django  </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'stepshop/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'stepshop/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'stepshop/js/custom.js' %}"></script>
    <script src="{% static 'stepshop/js/owl.js' %}"></script>
    <script src="{% static 'stepshop/js/isotope.js' %}"></script>
    <script src="{% static 'stepshop/js/flex-slider.js' %}"></script>


  </body>

</html>

project/stepshop/stepshop/templates/stepshop/contact.html
{% extends 'stepshop/base.html' %}
{% load static %}


{% block css %}
  <link rel="stylesheet" href="{% static 'stepshop/css/flex-slider.css' %}">
{% endblock %}


{% block content %}
    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="contact-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Contact Us</h1>
            </div>
          </div>
          <div style="width: 100%;">
            <div id="map">
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6321.929682145899!2d140.0032554784382!3d-66.66359949911663!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xaec6c681b100f26f%3A0xec9c22d97d3cd9c8!2z0JTRjtC80L7QvS3QtCfQrtGA0LLQuNC70YwsINCQ0L3RgtCw0YDQutGC0LjQutCw!5e0!3m2!1sru!2skz!4v1629350003558!5m2!1sru!2skz" width="100%" height="500px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <div class="container">
                <form id="contact" action="" method="post">
                  <div class="row">
                    <div class="col-md-6">
                      
                      {% if user.is_authenticated %}
                      <div class="col-md-12">
                      <fieldset>
                        <input name="subject" type="text" class="form-control" id="subject" style="width:35rem;" placeholder="Subject..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <textarea name="message" rows="6" class="form-control" id="message" style="width:35rem;" placeholder="Your message..." required=""></textarea>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="button">Send Message</button>
                      </fieldset>
                    </div>
                    {% endif %}
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->

{% endblock %}

project/stepshop/stepshop/templates/stepshop/index.html
{% extends 'stepshop/base.html' %}
{% load static %}

{% block content %}
<!-- Page Content -->
    <!-- Banner Starts Here -->
    <br>
    <div class="banner">
    </div>
    <!-- Banner Ends Here -->

    <!-- Featured Starts Here -->
    <div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Featured Items</h1>
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-carousel owl-theme">
              {% for item in products %}
                <a href="{% url 'products:product' item.pk %}">
                  <div class="featured-item">
                    <img src="/media/{{ item.image }}" alt="{{ item.short_desc }}">
                    <h4>{{ item.name }}</h4>
                    <h6>${{ item.price }}</h6>
                  </div>
                </a>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Featred Ends Here -->
{% endblock %}